name: nf-core-qtlmap-1.0dev
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - conda-forge::r-dplyr=0.8.0.1
  - conda-forge::r-optparse=1.6.1
  - bioconda::bioconductor-genomicranges=1.34.0
  - bioconda::bcftools=1.9
  - bioconda::tabix=0.2.6
  - bioconda::plink2=1.90b3.35
  - bioconda::csvtk=0.20.0
  - anaconda::pandas=1.0.3

